### ISSUE TITLE
Add publication page

### ISSUE THREAD

**Issue by bart1** [enram/hirad.science#6]
I just have this paper out https://doi.org/10.1111/2041-210X.14383 . As it acknowledges HiRad I wanted to add it the publications page but that does not exist yet. As I did not want to cause a mess I thought you might know the right command to add it

**Comment by bart1** [comment]
Thanks!

**Comment by peterdesmet** [comment]
Publication page is now live: https://hirad.science/publications/ (and might read that article on move2 😄)
